export const api_url = "https://cashback-back-end.herokuapp.com"
export const grant_type = "password"
export const client_id = "cashback-user"
export const client_secret = "NV2MfFAP4drPaHBC"
export const scope = "read write"